//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSeriesLibrary_Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeSeriesLibrary_Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;JOEBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;PER-CUM&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;2&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/01/1927 03:09:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Hour&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;1&lt;/TimeStepQuantity&gt;
        ///		&lt;Data&gt;
        ///12.3
        ///21.5
        ///32.7
        ///99.6
        ///90.1
        ///60.7
        ///50.0
        ///20.1
        ///12.4
        ///		&lt;/Data&gt;
        ///	&lt;/TimeSeries&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;BILLBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;INST-VAL&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;5&lt;/TraceNumber&gt;
        ///		&lt;StartDa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;JOEBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;PER-CUM&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;2&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/01/1927 03:09:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Hour&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;1&lt;/TimeStepQuantity&gt;
        ///		&lt;Data&gt;
        ///12.3
        ///21.5
        ///32.7
        ///99.6
        ///90.1
        ///60.7
        ///50.0
        ///20.1
        ///12.4
        ///		&lt;/Data&gt;
        ///	&lt;/TimeSeries&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;BILLBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;INST-VAL&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;5&lt;/TraceNumber&gt;
        ///		&lt;StartDa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
    }
}
