//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSeriesLibrary_Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeSeriesLibrary_Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;JOEBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;PER-CUM&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;2&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/01/1927 03:09:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Hour&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;1&lt;/TimeStepQuantity&gt;
        ///		&lt;Data&gt;
        ///12.3
        ///21.5
        ///32.7
        ///99.6
        ///90.1
        ///60.7
        ///50.0
        ///20.1
        ///12.4
        ///		&lt;/Data&gt;
        ///	&lt;/TimeSeries&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;BILLBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;INST-VAL&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;5&lt;/TraceNumber&gt;
        ///		&lt;StartDa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///  &lt;!--For testing multitrace import--&gt;
        ///  
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;ManyTrace&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;PER-CUM&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;2&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/01/1927 03:09:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Hour&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;1&lt;/TimeStepQuantity&gt;
        ///        &lt;Random&gt;^!@  #()?&lt;/Random&gt;
        ///      &lt;Data Trace=&quot;1&quot;&gt;
        ///12.3
        ///21.5
        ///32.7
        ///99.6
        ///90.1
        ///60.7
        ///50.0
        ///50.0
        ///20.1
        ///12.4
        ///        &lt;/Data&gt;
        ///      &lt;Data Trace=&quot;3&quot;&gt;
        ///32.3
        ///51.5
        ///52.7
        ///99.6
        ///90.1
        ///60. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///  &lt;!--For testing multitrace import--&gt;
        ///  
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;ManyTrace&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;PER-CUM&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;2&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/01/1927 03:09:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Month&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;1&lt;/TimeStepQuantity&gt;
        ///        &lt;Random&gt;^!@  #()?&lt;/Random&gt;
        ///      &lt;Data Trace=&quot;1&quot;&gt;
        ///12.3
        ///21.5
        ///32.7
        ///99.6
        ///90.1
        ///60.7
        ///50.0
        ///50.0
        ///20.1
        ///12.4
        ///        &lt;/Data&gt;
        ///      &lt;Data Trace=&quot;3&quot;&gt;
        ///32.3
        ///51.5
        ///52.7
        ///99.6
        ///90.1
        ///60 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///	&lt;Pattern&gt;
        ///		&lt;Name&gt;JOEBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;PER-CUM&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;2&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/01/1927 03:09:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Hour&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;1&lt;/TimeStepQuantity&gt;
        ///		&lt;Data&gt;
        ///12.3
        ///21.5
        ///32.7
        ///99.6
        ///90.1
        ///60.7
        ///50.0
        ///20.1
        ///12.4
        ///		&lt;/Data&gt;
        ///	&lt;/Pattern&gt;
        ///    &lt;Pattern&gt;
        ///		&lt;Name&gt;BILLBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;INST-VAL&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;5&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test4 {
            get {
                return ResourceManager.GetString("test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;JOEBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;PER-CUM&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;2&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;10/01/1927 03:09:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Hour&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;1&lt;/TimeStepQuantity&gt;
        ///		&lt;Data&gt;
        ///12.3
        ///21.5
        ///32.7
        ///99.6
        ///90.1
        ///60.7
        ///50.0
        ///20.1
        ///12.4
        ///		&lt;/Data&gt;
        ///	&lt;/TimeSeries&gt;
        ///    &lt;Pattern&gt;
        ///		&lt;Name&gt;BILLBLOW&lt;/Name&gt;
        ///		&lt;Units&gt;CFS&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;INST-VAL&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;5&lt;/TraceNumber&gt;
        ///		&lt;StartDa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test5 {
            get {
                return ResourceManager.GetString("test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Import&gt;
        ///	&lt;TimeSeries&gt;
        ///		&lt;Name&gt;aabbcc&lt;/Name&gt;
        ///		&lt;Units&gt;AFD&lt;/Units&gt;
        ///		&lt;TimeSeriesType&gt;INST-VAL&lt;/TimeSeriesType&gt;
        ///		&lt;TraceNumber&gt;22&lt;/TraceNumber&gt;
        ///		&lt;StartDate&gt;1/01/1930 11:59:00&lt;/StartDate&gt;
        ///		&lt;TimeStepUnit&gt;Irregular&lt;/TimeStepUnit&gt;
        ///		&lt;TimeStepQuantity&gt;337&lt;/TimeStepQuantity&gt;
        ///                &lt;OldManTag&gt;&lt;/OldManTag&gt;
        ///                &lt;Schlap&gt;Spoing-oing-oing&lt;/Schlap&gt;
        ///		&lt;Data&gt;
        ///01/01/1930 10:59:00 312.5
        ///01/01/1930 23:59:00 321.7
        ///01/02/1930 11:59:00 332.8
        ///01/02/1930 23:59:00 399.8
        ///01/03/1930 11:59:00 390 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test6 {
            get {
                return ResourceManager.GetString("test6", resourceCulture);
            }
        }
    }
}
